language: ruby

before_install:
  - gem install bundler

cache:
  directories:
    - bundle

rvm:
  - 2.7

jobs:
  include:
    - stage: rspec test
      script: bundle exec rspec
    - stage: publish docs
      if: branch = master
      script: bundle exec pantograph pipeline --verbose
    # - stage: publish gem
      # if: branch = master
      # script: gem build pantograph.gemspec && gem push 